sonar.organization=sanndeepgc
sonar.projectKey=sanndeepgc_open-ths-kafka-docker
sonar.projectName=open-ths-kafka-docker

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/.git/**,\
**/.github/**,\
**/node_modules/**,\
**/target/**,\
**/build/**,\
**/dist/**,\
**/coverage/**,\
**/*.min.js
